### ISSUE TITLE
Error in Tenant/Monitor

### ISSUE THREAD

**Issue by hadimansouri** [pluf/core#74]
An exception is thrown in the Tenant/Monitor repeatedly:

`
unsupported error in system:exception 'PlufErrorHandlerException' with message 'exec() has been disabled for security reasons' in /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Tenant/Monitor.php:41 Stack trace: #0 [internal function]: PlufErrorHandler(2, 'exec() has been...', '/home/psimorgh/...', 41, Array) #1 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Tenant/Monitor.php(41): exec('du -sk /home/ps...') #2 [internal function]: Tenant_Monitor::storage(Object(Pluf_HTTP_Request), Array) #3 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Pluf/Monitor.php(133): call_user_func_array(Array, Array) #4 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Monitor/Views.php(127): Pluf_Monitor->invoke(Object(Pluf_HTTP_Request), Array) #5 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Pluf/Dispatcher.php(265): Monitor_Views::call(Object(Pluf_HTTP_Request), Array) #6 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Pluf/Dispatcher.php(179): Pluf_Dispatcher::send(Object(Pluf_HTTP_Request), Array, Array) #7 /home/psimorgh/public_html/develop.digidoki.com/vendor/pluf/core/src/Pluf/Dispatcher.php(75): Pluf_Dispatcher::match(Object(Pluf_HTTP_Request)) #8 /home/psimorgh/public_html/develop.digidoki.com/index.php(53): Pluf_Dispatcher::dispatch('api/monitor/ten...') #9 {main}
`

**Comment by hadimansouri** [comment]
I change method for computing size of used memory.
